### ISSUE TITLE
bundle exec spoom coverage --save fails with an error about an uninitialized constant

### ISSUE THREAD

**Issue by connorshea** [Shopify/spoom#57]
**Describe the bug**
Running `spoom coverage --save` is failing locally for me on macOS for some reason.

For whatever reason, it fails locally but not in my CI (Ruby 2.7.2, same versions of all the gems, same Bundler version, etc. only real difference is the RubyGems version and the fact that it's being run on Linux). The app I'm getting this error on is https://github.com/connorshea/vglist

**To Reproduce**
Spoom version: 1.0.7
Ruby: 2.7.2
macOS: 10.15.7 (Catalina)

1. Clone `https://github.com/connorshea/vglist`
2. Run `bundle install`
3. Run `bundle exec spoom coverage --save`
4. See error:

```
vglist connorshea$ bundle exec spoom coverage --save
Sorbet static: 0.5.6189
Sorbet runtime: 0.5.6189

Content:
  files: 664
  modules: 2418
  classes: 7394
  methods: 84888

Sigils:
  ignore: 16 (2%)
  false: 165 (25%)
  true: 247 (37%)
  strict: 164 (25%)
  strong: 72 (11%)

Methods:
  with signature: 12232 (14%)
  without signature: 72656 (86%)

Calls:
  typed: 5274 (75%)
  untyped: 1790 (25%)
bundler: failed to load command: spoom (/Users/connorshea/.rbenv/versions/2.7.2/bin/spoom)
Traceback (most recent call last):
	27: from /Users/connorshea/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
	26: from /Users/connorshea/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
	25: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
	24: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	23: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
	22: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'
	21: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	20: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
	19: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	18: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	17: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	16: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:497:in `exec'
	15: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
	14: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
	13: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
	12: from /Users/connorshea/.rbenv/versions/2.7.2/bin/spoom:23:in `<top (required)>'
	11: from /Users/connorshea/.rbenv/versions/2.7.2/bin/spoom:23:in `load'
	10: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spoom-1.0.7/exe/spoom:7:in `<top (required)>'
	 9: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	 8: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 7: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 6: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	 5: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	 4: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	 3: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 2: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 1: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spoom-1.0.7/lib/spoom/cli/coverage.rb:27:in `snapshot': uninitialized constant Spoom::Cli::Coverage::FileUtils (NameError)
Did you mean?  FileTest
```

**Expected behavior**
The coverage command should create a JSON file in `spoom_data/` with coverage information.

**Comment by Morriar** [comment]
@connorshea I couldn't reproduce with the steps you provided but I created #58 that might solve your problem. Can you confirm please?
